---
- name: Deploy Minio stack to Docker Swarm
  hosts: int_swarm_managers[0]
  gather_facts: false
  become: true
  tasks:
    # Set up networks for attaching services
    - name: Ensure 'proxy' network exists and attachable
      community.docker.docker_network:
        name: proxy
        driver: overlay
        attachable: true
        state: present
    - name: Ensure 'minio-net' network exists and attachable
      community.docker.docker_network:
        name: minio-net
        driver: overlay
        attachable: true
        state: present
    # Encrypted vars
    - name: Include encrypted variables
      ansible.builtin.include_vars:
        file: group_vars/secrets.yml

    # Begin configuring the minio stack
    - name: Create temporary directory for compose stack
      ansible.builtin.tempfile:
        state: directory
        suffix: _compose
      register: temp_dir_result
    - name: Render and copy compose file as a stack to temp dir on manager
      ansible.builtin.template:
        src: templates/minio-stack.yml.j2
        dest: "{{ temp_dir_result.path }}/minio.yml"
        
    - name: Deploy Minio stack to Docker Swarm
      community.docker.docker_stack:
        state: present
        name: minio
        compose: "{{ temp_dir_result.path }}/minio.yml"
      register: stack_deploy_result

    - name: Clean up temporary directory
      ansible.builtin.file:
        path: "{{ temp_dir_result.path }}"
        state: absent
      when: stack_deploy_result is succeeded
