---
- name: Deploy Redis stack to Docker Swarm
  hosts: int_swarm_managers[0]
  become: true
  gather_facts: false
  tasks:
    # Set up networks for attaching services
    - name: Ensure 'redis' network exists and attachable
      community.docker.docker_network:
        name: redis
        driver: overlay
        attachable: true
        state: present
    # Encrypted vars
    - name: Include encrypted variables
      ansible.builtin.include_vars:
        file: group_vars/secrets.yml

    # Create required directories on shared storage
    - name: Ensure Redis data directory exists
      ansible.builtin.file:
        path: /mnt/shared/redis
        state: directory
        owner: 1001
        group: 0
        mode: '0755'

    # Begin configuring the Redis stack
    - name: Create temporary directory for compose stack
      ansible.builtin.tempfile:
        state: directory
        suffix: _compose
      register: temp_dir_result

    - name: Render and copy compose file as a stack to temp dir on manager
      ansible.builtin.template:
        src: templates/redis-stack.yml.j2
        dest: "{{ temp_dir_result.path }}/redis-stack.yml"

    - name: Deploy Redis stack to Docker Swarm
      community.docker.docker_stack:
        state: present
        name: redis
        compose: "{{ temp_dir_result.path }}/redis-stack.yml"
      register: stack_deploy_result

    - name: Clean up temporary directory
      ansible.builtin.file:
        path: "{{ temp_dir_result.path }}"
        state: absent
      when: stack_deploy_result is succeeded
