services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/kavita/config:/config
      - /path/to/data:/data #optional
    ports:
      - 5000:5000
    restart: unless-stopped
