services:
  pgadmin:
    image: dpage/pgadmin4:9.4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: changeme
      PGADMIN_CONFIG_DATABASE_URI: postgresql://postgres:password@pgbouncer:6432/postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - backend
      - proxy

volumes:
  pgadmin_data:

networks:
  backend:
    external: true
  proxy:
    external: true