version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333" # Qdrant API port
      - "6334:6334" # Qdrant gRPC port
    volumes:
      - ./qdrant_storage:/qdrant/storage # Persistent storage for data
