networks:
  redis:
    external: true

services:
  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - redis
    deploy:
      replicas: 1
